### ISSUE TITLE
Giphy is crashing while viewing clips

### ISSUE THREAD

**Issue by ursnj** [Giphy/giphy-react-native-sdk#77]
## To Reproduce

2022-09-21 14:38:00.246 10779-10779/njsolutions.worklage E/AndroidRuntime: FATAL EXCEPTION: main
    Process: njsolutions.worklage, PID: 10779
    java.lang.NoSuchMethodError: No virtual method buildUponParameters()Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector$ParametersBuilder; in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in /data/app/~~c72wE7SqaaB_5GHwG3Lehw==/njsolutions.worklage-g1YHMxNgI8gb0de5Z5oRBg==/base.apk!classes9.dex)
        at com.giphy.sdk.ui.views.GPHVideoPlayer.loadMedia(GPHVideoPlayer.kt:253)
        at com.giphy.sdk.ui.views.GPHVideoPlayer.loadMedia$default(GPHVideoPlayer.kt:211)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.showVideoAttributionScreen(GiphyDialogFragment.kt:1403)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.onGifSelected(GiphyDialogFragment.kt:1129)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.access$onGifSelected(GiphyDialogFragment.kt:58)
        at com.giphy.sdk.ui.views.GiphyDialogFragment$setupGifsRecycler$2.invoke(GiphyDialogFragment.kt:483)
        at com.giphy.sdk.ui.views.GiphyDialogFragment$setupGifsRecycler$2.invoke(GiphyDialogFragment.kt:58)
        at com.giphy.sdk.ui.universallist.SmartGridRecyclerView$onItemSelectedListener$1.invoke(SmartGridRecyclerView.kt:126)
        at com.giphy.sdk.ui.universallist.SmartGridRecyclerView$onItemSelectedListener$1.invoke(SmartGridRecyclerView.kt:34)
        at com.giphy.sdk.ui.universallist.SmartGridAdapter$onCreateViewHolder$1.onClick(SmartGridAdapter.kt:49)
        at android.view.View.performClick(View.java:7467)
        at android.view.View.performClickInternal(View.java:7444)
        at android.view.View.access$3700(View.java:840)
        at android.view.View$PerformClick.run(View.java:28831)
        at android.os.Handler.handleCallback(Handler.java:978)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loopOnce(Looper.java:238)
        at android.os.Looper.loop(Looper.java:357)
        at android.app.ActivityThread.main(ActivityThread.java:8090)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

## Expected behavior

it was working before, but started crashing recently.

## Actual Behavior

it should not crash

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Giphy React Native SDK version: 1.9.1
- React Native version: 0.69.3
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Device

## Reproducible Demo

https://user-images.githubusercontent.com/28749151/191496954-f824e57f-3caa-4f5f-86ea-3c0864fa9818.mp4

**Comment by pshoniuk** [comment]
Hi @ursnj, thanks for the report!

It looks like you have installed another package that also uses ExoPlayer. But this package uses a different version of ExoPlayer, which is incompatible with the GIPHY SDK. To check this, you can inspect the output of this command running from the `android` folder: 
```
./gradlew app:androidDependencies 
```

**Comment by ursnj** [comment]
thanks for quick response @pshoniuk , but all of my exoplayer dependecies are in 2.18.1. 

![Screenshot 2022-09-21 at 11 54 02 PM](https://user-images.githubusercontent.com/28749151/191581878-165d55e6-5f39-4b8d-b260-e377e164ee56.png)

**Comment by ursnj** [comment]
Fixed with https://github.com/Giphy/giphy-react-native-sdk/pull/78
